### ISSUE TITLE
terraform tries to apply everything from examples directory

### ISSUE THREAD

**Issue by yanndegat** [ovh/terraform-ovh-publiccloud-network#2]
related to issue #1  encounter by @gavvvr
request for more info

**Comment by gavvvr** [comment]
Here is my simplest usage scenario of the module (sensitive data removed):
```
variable "user_name" {}
variable "password" {}

variable "region" {}

provider "openstack" {
  auth_url = "https://auth.cloud.ovh.net/v3" # Authentication URL
  domain_name = "default" # Domain Name - Always "default" for OVH
  alias = "ovh"
  region = "${var.region}"
  user_name   = "${var.user_name}"
  password    = "${var.password}"
}

provider "ovh" {
  application_key=""
  application_secret=""
  consumer_key=""
  endpoint = "ovh-eu"
  alias = "ovh"
}

resource "openstack_compute_keypair_v2" "test_keypair" {
  provider = "openstack.ovh" # Precise the provider name
  name = "test_keypair" # SSH key's name
  public_key = "${file("~/.ssh/id_rsa.pub")}" # Path of your SSH key
}

module "network" {
  source = "ovh/publiccloud-network/ovh"

  providers = {
    ovh = "ovh.ovh"
    openstack = "openstack.ovh"
  }

  project_id      = ""
  vrack_id        = "vrack_id"

  name            = "private-network"
  cidr            = "10.0.0.0/16"
  region          = "${var.region}"
  public_subnets  = ["10.0.0.0/24", "10.0.10.0/24"]
  private_subnets = ["10.0.1.0/24", "10.0.11.0/24"]

  enable_nat_gateway  = true
  enable_bastion_host = true

  ssh_public_keys = ["${openstack_compute_keypair_v2.test_keypair.public_key}"]

  metadata = {
    Terraform   = "true"
    Environment = "stage"
  }
}
```

I run `terraform plan` and see there are 23 items to create.
Among them:
* module.network.openstack_compute_instance_v2.bastion
* module.network.openstack_compute_instance_v2.nats[1]
* module.network.openstack_compute_instance_v2.nats[0]

Thus 3 instances with CoreOS. I supposed it is from example dir, may be I am wrong. Did not have much time to play with it.

I found this repo after having troubles with this instruction:
https://docs.ovh.com/gb/en/public-cloud/how-to-use-terraform/
If I try to create a private network using instructions in the link above, my VM's do not have private IPs assigned (there are interfaces, but no IPv4 assigned even though they are hard-coded). That's why I decided to try this module found on github.

**Comment by yanndegat** [comment]
hi @gavvvr 
ok, so its not a bug

effectively, this module creates instances, in addition to pure networking resources.

Compared to other cloud providers, OVH cloud doesnt provide private L3 network
but private L2 network. Meaning, you dont have a router and you have to manage your routes 
yourself.
Additionaly, it doesn't provide Managed Nat Gateways either.

Meaning: when you create a private network, if you dont create a nat gw, your vms wont have a route to internet. If you don't create a bastion host, you wont be able to ssh into your boxes.

thats what the nat/bastion vms are made for.
but they are optional & disabled by default.

you activated the spawn of these vms by setting these two attributes:
- enable_nat_gateway  = true
- enable_bastion_host = true
